import './globals.css';
import { Inter } from 'next/font/google';
//INTERNAL IMPORT
import { NavBar, Footer, Service } from '../components/componentIndex';
import Home from './page';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <NavBar />
        <Home />
        <Service />
        <Footer />
      </body>
    </html>
  );
}
